from models import *

MOCK_REQUEST = InputData(rooms=[InputDataRooms(location='ECS 128', capacity=18, equipment=[]),
                                      InputDataRooms(location='ECS 130', capacity=34, equipment=[]),
                                      InputDataRooms(location='ECS 104', capacity=60, equipment=[]),
                                      InputDataRooms(location='ECS 108', capacity=60, equipment=[]),
                                      InputDataRooms(location='ECS 124', capacity=78, equipment=[]),
                                      InputDataRooms(location='ECS 116', capacity=117, equipment=[]),
                                      InputDataRooms(location='ECS 125', capacity=151, equipment=[]),
                                      InputDataRooms(location='ECS 123', capacity=299, equipment=[]),
                                      InputDataRooms(location='BWC A104', capacity=140, equipment=[]),
                                      InputDataRooms(location='BWC B150', capacity=358, equipment=[]),
                                      InputDataRooms(location='ELL 161', capacity=24, equipment=[]),
                                      InputDataRooms(location='ELL 160', capacity=48, equipment=[]),
                                      InputDataRooms(location='ELL 162', capacity=54, equipment=[]),
                                      InputDataRooms(location='ELL 060', capacity=68, equipment=[]),
                                      InputDataRooms(location='ELL 061', capacity=68, equipment=[]),
                                      InputDataRooms(location='ELL 062', capacity=80, equipment=[]),
                                      InputDataRooms(location='ELL 167', capacity=148, equipment=[]),
                                      InputDataRooms(location='ELL 168', capacity=180, equipment=[]),
                                      InputDataRooms(location='CLE A308', capacity=12, equipment=[]),
                                      InputDataRooms(location='CLE C116', capacity=12, equipment=[]),
                                      InputDataRooms(location='CLE C118', capacity=12, equipment=[]),
                                      InputDataRooms(location='CLE D285', capacity=14, equipment=[]),
                                      InputDataRooms(location='CLE B215', capacity=20, equipment=[]),
                                      InputDataRooms(location='CLE B315', capacity=20, equipment=[]),
                                      InputDataRooms(location='CLE B415', capacity=20, equipment=[]),
                                      InputDataRooms(location='CLE C316', capacity=20, equipment=[]),
                                      InputDataRooms(location='CLE A325', capacity=21, equipment=[]),
                                      InputDataRooms(location='CLE D130', capacity=21, equipment=[]),
                                      InputDataRooms(location='CLE D134', capacity=21, equipment=[]),
                                      InputDataRooms(location='CLE A221', capacity=22, equipment=[]),
                                      InputDataRooms(location='CLE A330', capacity=22, equipment=[]),
                                      InputDataRooms(location='CLE C214', capacity=22, equipment=[]),
                                      InputDataRooms(location='CLE A326', capacity=23, equipment=[]),
                                      InputDataRooms(location='CLE A118', capacity=24, equipment=[]),
                                      InputDataRooms(location='CLE D125', capacity=27, equipment=[]),
                                      InputDataRooms(location='CLE D131', capacity=27, equipment=[]),
                                      InputDataRooms(location='CLE C111', capacity=28, equipment=[]),
                                      InputDataRooms(location='CLE C113', capacity=28, equipment=[]),
                                      InputDataRooms(location='CLE A312', capacity=30, equipment=[]),
                                      InputDataRooms(location='CLE A329', capacity=30, equipment=[]),
                                      InputDataRooms(location='CLE C115', capacity=30, equipment=[]),
                                      InputDataRooms(location='CLE D126', capacity=30, equipment=[]),
                                      InputDataRooms(location='CLE A217', capacity=31, equipment=[]),
                                      InputDataRooms(location='CLE A216', capacity=32, equipment=[]),
                                      InputDataRooms(location='CLE C108', capacity=32, equipment=[]),
                                      InputDataRooms(location='CLE A225', capacity=35, equipment=[]),
                                      InputDataRooms(location='CLE C109', capacity=35, equipment=[]),
                                      InputDataRooms(location='CLE D132', capacity=36, equipment=[]),
                                      InputDataRooms(location='CLE C110', capacity=42, equipment=[]),
                                      InputDataRooms(location='CLE A208', capacity=43, equipment=[]),
                                      InputDataRooms(location='CLE A320', capacity=45, equipment=[]),
                                      InputDataRooms(location='CLE A313', capacity=46, equipment=[]),
                                      InputDataRooms(location='CLE A317', capacity=47, equipment=[]),
                                      InputDataRooms(location='CLE A207', capacity=59, equipment=[]),
                                      InputDataRooms(location='CLE C112', capacity=69, equipment=[]),
                                      InputDataRooms(location='CLE A224', capacity=86, equipment=[]),
                                      InputDataRooms(location='CLE A127', capacity=105, equipment=[]),
                                      InputDataRooms(location='COR A132', capacity=14, equipment=[]),
                                      InputDataRooms(location='COR A128', capacity=32, equipment=[]),
                                      InputDataRooms(location='COR B145', capacity=36, equipment=[]),
                                      InputDataRooms(location='COR B111', capacity=50, equipment=[]),
                                      InputDataRooms(location='COR A129', capacity=61, equipment=[]),
                                      InputDataRooms(location='COR B107', capacity=60, equipment=[]),
                                      InputDataRooms(location='COR A229', capacity=62, equipment=[]),
                                      InputDataRooms(location='COR A225', capacity=64, equipment=[]),
                                      InputDataRooms(location='COR A125', capacity=65, equipment=[]),
                                      InputDataRooms(location='COR B129', capacity=67, equipment=[]),
                                      InputDataRooms(location='COR A121', capacity=71, equipment=[]),
                                      InputDataRooms(location='COR B108', capacity=71, equipment=[]),
                                      InputDataRooms(location='COR B112', capacity=71, equipment=[]),
                                      InputDataRooms(location='COR B143', capacity=77, equipment=[]),
                                      InputDataRooms(location='COR B135', capacity=80, equipment=[]),
                                      InputDataRooms(location='COR A120', capacity=81, equipment=[]),
                                      InputDataRooms(location='COR A221', capacity=93, equipment=[]),
                                      InputDataRooms(location='CUN 146', capacity=58, equipment=[]),
                                      InputDataRooms(location='CON 020', capacity=20, equipment=[]),
                                      InputDataRooms(location='DSB C114', capacity=20, equipment=[]),
                                      InputDataRooms(location='DSB C124', capacity=20, equipment=[]),
                                      InputDataRooms(location='DSB C126', capacity=35, equipment=[]),
                                      InputDataRooms(location='DSB C130', capacity=35, equipment=[]),
                                      InputDataRooms(location='DSB C128', capacity=35, equipment=[]),
                                      InputDataRooms(location='DSB C108', capacity=45, equipment=[]),
                                      InputDataRooms(location='DSB C116', capacity=64, equipment=[]),
                                      InputDataRooms(location='DSB C122', capacity=64, equipment=[]),
                                      InputDataRooms(location='DSB C118', capacity=74, equipment=[]),
                                      InputDataRooms(location='DSB C103', capacity=186, equipment=[]),
                                      InputDataRooms(location='DTB A102', capacity=110, equipment=[]),
                                      InputDataRooms(location='DTB A104', capacity=110, equipment=[]),
                                      InputDataRooms(location='DTB A110', capacity=140, equipment=[]),
                                      InputDataRooms(location='DTB A120', capacity=250, equipment=[]),
                                      InputDataRooms(location='FIN 209', capacity=20, equipment=[]),
                                      InputDataRooms(location='FIN 104', capacity=28, equipment=[]),
                                      InputDataRooms(location='FIN 103', capacity=50, equipment=[]),
                                      InputDataRooms(location='FRA 159', capacity=284, equipment=[]),
                                      InputDataRooms(location='HCK 105', capacity=215, equipment=[]),
                                      InputDataRooms(location='HCK 116', capacity=40, equipment=[]),
                                      InputDataRooms(location='HCK 110', capacity=46, equipment=[]),
                                      InputDataRooms(location='HSD A250', capacity=24, equipment=[]),
                                      InputDataRooms(location='HSD A264', capacity=30, equipment=[]),
                                      InputDataRooms(location='HSD A270', capacity=30, equipment=[]),
                                      InputDataRooms(location='HSD A240', capacity=154, equipment=[]),
                                      InputDataRooms(location='MAC A326', capacity=16, equipment=[]),
                                      InputDataRooms(location='MAC A144', capacity=317, equipment=[]),
                                      InputDataRooms(location='MAC D010', capacity=45, equipment=[]),
                                      InputDataRooms(location='MAC D016', capacity=40, equipment=[]),
                                      InputDataRooms(location='MAC D107', capacity=15, equipment=[]),
                                      InputDataRooms(location='MAC D105', capacity=17, equipment=[]),
                                      InputDataRooms(location='MAC D109', capacity=20, equipment=[]),
                                      InputDataRooms(location='MAC D111', capacity=29, equipment=[]),
                                      InputDataRooms(location='MAC D203', capacity=34, equipment=[]),
                                      InputDataRooms(location='MAC D101', capacity=36, equipment=[]),
                                      InputDataRooms(location='MAC D103', capacity=36, equipment=[]),
                                      InputDataRooms(location='MAC D114', capacity=37, equipment=[]),
                                      InputDataRooms(location='MAC D110', capacity=47, equipment=[]),
                                      InputDataRooms(location='MAC D283', capacity=55, equipment=[]),
                                      InputDataRooms(location='MAC D116', capacity=59, equipment=[]),
                                      InputDataRooms(location='MAC D115', capacity=60, equipment=[]),
                                      InputDataRooms(location='MAC D207', capacity=79, equipment=[]),
                                      InputDataRooms(location='MAC D287', capacity=40, equipment=[]),
                                      InputDataRooms(location='MAC D288', capacity=79, equipment=[]),
                                      InputDataRooms(location='MCK 155', capacity=38, equipment=[]),
                                      InputDataRooms(location='MCK 150', capacity=107, equipment=[]),
                                      InputDataRooms(location='B&E 363', capacity=30, equipment=[])],
                               timeslots=[InputDataTimeslots(day=["Monday", "Thursday"], length=80, startTime=830),
                                          InputDataTimeslots(day=["Monday", "Thursday"], length=80, startTime=1000),
                                          InputDataTimeslots(day=["Monday", "Thursday"], length=80, startTime=1130),
                                          InputDataTimeslots(day=["Monday", "Thursday"], length=80, startTime=1300),
                                          InputDataTimeslots(day=["Monday", "Thursday"], length=80, startTime=1430),
                                          InputDataTimeslots(day=["Monday", "Thursday"], length=80, startTime=1600),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=830),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=930),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=1030),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=1130),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=1230),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=1330),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=1430),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=1530),
                                          InputDataTimeslots(day=["Tuesday", "Wednesday", "Friday"], length=50,
                                                             startTime=1630)
                                          ],
                               courses=[
                                   InputDataCourses(coursename='ECE 216', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=119),
                                   InputDataCourses(coursename='ECE 220', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=153),
                                   InputDataCourses(coursename='ECE 241', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=238),
                                   InputDataCourses(coursename='ECE 242', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=166),
                                   InputDataCourses(coursename='ECE 250', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=146),
                                   InputDataCourses(coursename='ECE 255', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=59),
                                   InputDataCourses(coursename='ECE 260', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=58),
                                   InputDataCourses(coursename='ECE 299', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=39),
                                   InputDataCourses(coursename='ECE 300', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=160),
                                   InputDataCourses(coursename='ECE 310', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=169),
                                   InputDataCourses(coursename='ECE 320', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=72),
                                   InputDataCourses(coursename='ECE 330', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=119),
                                   InputDataCourses(coursename='ECE 340', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=183),
                                   InputDataCourses(coursename='ECE 350', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=60),
                                   InputDataCourses(coursename='ECE 355', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=172),
                                   InputDataCourses(coursename='ECE 356', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=77),
                                   InputDataCourses(coursename='ECE 360', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=152),
                                   InputDataCourses(coursename='ECE 365', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=57),
                                   InputDataCourses(coursename='ECE 370', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=77),
                                   InputDataCourses(coursename='ECE 380', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=45),
                                   InputDataCourses(coursename='ECE 399', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=159),
                                   InputDataCourses(coursename='ECE 403', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=167),
                                   InputDataCourses(coursename='ECE 410', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=196),
                                   InputDataCourses(coursename='ECE 455', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=179),
                                   InputDataCourses(coursename='ECE 458', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=68),
                                   InputDataCourses(coursename='ECE 463', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=128),
                                   InputDataCourses(coursename='ECE 488', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=142),
                                   InputDataCourses(coursename='ECE 499', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=37),
                                   InputDataCourses(coursename='SENG 275', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=209),
                                   InputDataCourses(coursename='SENG 426', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=194),
                                   InputDataCourses(coursename='SENG 440', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=85),
                                   InputDataCourses(coursename='SENG 468', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=227),
                                   InputDataCourses(coursename='SENG 499', noScheduleOverlap=None, lecturesNumber=None,
                                                    labsNumber=None, tutorialsNumber=None, capacity=160)]
                               ,
                               professors=[InputDataProfessors(name='Adams, Michael', courses=[], timePreferences=[],
                                                               coursePreferences=[3, 0, 0, 0, 0, 3, 6, 0, 0, 4, 3, 0, 0, 0, 0, 0, 0, 4, 3, 0, 0, 0, 0, 1, 0, 0, 4, 0, 0, 0, 0, 3, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Agathoklis, Panajotis', courses=[],
                                                               timePreferences=[], coursePreferences=[3, 0, 0, 0, 3, 0, 6, 0, 4, 0, 0, 0, 0, 0, 0, 6, 0, 0, 3, 0, 2, 0, 6, 4, 0, 0, 0, 0, 0, 0, 0, 3, 6],
                                                               dayPreferences=[], equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='AlTawy, Riham', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 0, 4], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Baniasadi, Amirali', courses=[],
                                                               timePreferences=[], coursePreferences=[0, 0, 0, 4, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 4, 0, 3, 0, 0, 0, 0, 0, 0, 6, 2, 4, 0, 0, 0, 0, 3, 0, 0],
                                                               dayPreferences=[], equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Bornemann, Jens', courses=[], timePreferences=[],
                                                               coursePreferences=[3, 1, 4, 0, 4, 4, 3, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 3, 0, 0, 5, 1, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Branzan Albu, Alexandra', courses=[],
                                                               timePreferences=[], coursePreferences=[0, 0, 2, 3, 0, 0, 5, 0, 0, 4, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 5, 0, 0, 5],
                                                               dayPreferences=[], equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Cai, Lin', courses=[], timePreferences=[],
                                                               coursePreferences=[4, 4, 0, 3, 1, 3, 4, 4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Capson, David', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 6, 0, 3, 4, 0, 0, 0, 3, 4, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4, 4], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Darcie, Ted', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3, 2, 0, 4, 0, 0, 0, 0, 0, 0, 4, 0, 3, 4, 0, 3, 0, 0, 0, 4, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Dimopoulos, Nikitas', courses=[],
                                                               timePreferences=[], coursePreferences=[1, 0, 4, 0, 2, 0, 0, 0, 0, 1, 3, 4, 3, 0, 6, 1, 6, 0, 3, 0, 0, 4, 0, 0, 0, 0, 0, 5, 4, 6, 0, 0, 0],
                                                               dayPreferences=[], equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Dong, Xiaodai', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 6, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 6, 0, 0, 6, 0, 0, 5, 6, 4, 0, 0, 0, 2, 4, 0, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Driessen, Peter', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 2, 0, 0, 4, 0, 0, 0, 0, 3, 1, 3, 0, 0, 4, 0, 3, 0, 0, 1], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Gebali, Fayez', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 6, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 6, 0, 5], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Gordon, Reuven', courses=[], timePreferences=[],
                                                               coursePreferences=[3, 0, 6, 0, 0, 0, 4, 0, 1, 0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 6, 4, 4, 3], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Gulliver, Aaron', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 3, 6, 0, 0, 4, 4, 0, 0, 6, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Li, Kin Fun', courses=[], timePreferences=[],
                                                               coursePreferences=[1, 0, 6, 6, 3, 0, 3, 0, 4, 0, 4, 0, 0, 0, 1, 0, 0, 0, 4, 5, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 3, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Lu, Tao', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 4, 4, 0, 0, 4, 4, 0, 0, 0, 0, 3, 3, 4, 0, 0, 0, 0, 6, 2, 0, 0, 0, 3, 0, 4, 0, 0, 0, 4, 0, 4, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='McGuire, Michael', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 3, 0, 6, 0, 0, 4, 3, 0, 3, 0, 4, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Neville, Stephen', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 6, 0, 4, 0, 3, 0, 3, 0, 2, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 4, 3, 4, 3, 0, 0, 0, 0, 4, 0, 3], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Papadopoulos, Christo', courses=[],
                                                               timePreferences=[], coursePreferences=[0, 0, 0, 3, 3, 0, 0, 0, 4, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 6, 0, 0, 0, 1, 4, 6, 3, 0, 0],
                                                               dayPreferences=[], equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Popli, Navneet', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 4, 0, 3, 0, 0, 0, 0, 0, 0, 6, 0, 0, 5, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Rakhmatov, Daler', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Saidaminov, Makhsud', courses=[],
                                                               timePreferences=[], coursePreferences=[0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 4, 4, 1, 0, 3, 1, 0, 0, 4, 0, 0, 0, 3, 5, 1, 0, 0, 0, 0, 0, 4],
                                                               dayPreferences=[], equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Shuja, Sana', courses=[], timePreferences=[],
                                                               coursePreferences=[6, 0, 4, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1, 0, 0, 2, 0, 6, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Sima, Mihai', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 6, 0, 3, 4, 3, 0, 4, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 4, 0, 0, 4, 0, 0, 2, 0, 0, 0, 0, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Smith, Levi', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 4, 0, 0, 6, 2, 0, 6, 0, 3, 3, 0, 0, 0, 0, 0, 1], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='So, Poman', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 3, 4, 3, 1, 0, 0, 6, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Thirumarai Chelvan, Ilamparithi', courses=[],
                                                               timePreferences=[], coursePreferences=[0, 6, 0, 0, 0, 0, 0, 0, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 4, 0, 0, 0, 0, 6, 6, 0, 0, 0, 0],
                                                               dayPreferences=[], equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Traore, Issa', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 6, 0, 4, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3),
                                           InputDataProfessors(name='Yang, Hong-Chuan', courses=[], timePreferences=[],
                                                               coursePreferences=[0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 4, 6, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0], dayPreferences=[],
                                                               equipmentPreferences=[], load=3)
                                           ],
                               dimensions=InputDataDimensions(courses=33, times=15, teachers=30, rooms=123),
                               preferences=[
                                   [0, 0, 0, 0, 0, 0, 195, 195, 0, 100, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 40, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0, 0, 20],
                                   [0, 0, 0, 0, 40, 0, 0, 40, 0, 40, 0, 40, 0, 0, 0, 0, 195, 0, 0, 20, 40, 0, 0, 0, 0,
                                    0, 0, 39, 0, 0, 0, 0, 0],
                                   [0, 0, 40, 39, 0, 78, 20, 0, 0, 40, 78, 0, 0, 0, 40, 78, 0, 0, 0, 0, 0, 20, 0, 0, 40,
                                    0, 0, 0, 0, 0, 0, 0, 20],
                                   [0, 0, 195, 78, 100, 100, 0, 20, 0, 78, 40, 0, 0, 78, 100, 78, 0, 0, 0, 0, 40, 195,
                                    195, 100, 40, 0, 0, 0, 0, 0, 0, 0, 0],
                                   [195, 78, 0, 0, 78, 0, 20, 40, 195, 78, 40, 195, 78, 78, 0, 0, 0, 78, 0, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                                   [0, 0, 0, 0, 0, 20, 100, 20, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 195, 40, 0, 0, 40,
                                    0, 0, 39, 0, 0, 0, 0, 20],
                                   [0, 0, 0, 0, 0, 0, 40, 0, 0, 20, 0, 40, 0, 78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 195,
                                    195, 0, 0, 0, 0, 0, 0, 0],
                                   [0, 0, 195, 0, 40, 100, 0, 0, 0, 39, 0, 0, 0, 0, 100, 0, 195, 0, 0, 0, 0, 0, 0, 40,
                                    0, 0, 0, 0, 0, 0, 0, 0, 0],
                                   [40, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0],
                                   [0, 0, 40, 0, 195, 40, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 195, 40,
                                    0, 0, 39, 0, 0, 0, 0, 0],
                                   [0, 0, 0, 0, 20, 0, 40, 0, 20, 100, 0, 0, 0, 100, 0, 0, 39, 0, 0, 0, 39, 39, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0, 0, 0],
                                   [0, 0, 0, 0, 0, 40, 40, 0, 0, 20, 0, 0, 40, 0, 40, 0, 195, 195, 0, 0, 78, 0, 0, 0,
                                    195, 195, 0, 100, 0, 0, 0, 0, 0],
                                   [0, 0, 78, 0, 78, 78, 40, 0, 40, 40, 0, 40, 0, 40, 78, 0, 78, 40, 0, 0, 0, 0, 0, 0,
                                    0, 195, 0, 20, 0, 0, 0, 0, 0],
                                   [78, 195, 0, 0, 40, 0, 40, 0, 40, 20, 78, 40, 40, 195, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0, 0, 0, 0],
                                   [0, 0, 0, 0, 0, 0, 39, 0, 0, 39, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 78, 0, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0],
                                   [0, 0, 195, 78, 39, 195, 0, 0, 0, 0, 0, 0, 0, 0, 78, 78, 0, 0, 0, 0, 0, 0, 0, 78, 0,
                                    0, 0, 39, 0, 0, 0, 78, 0],
                                   [40, 78, 0, 0, 78, 0, 20, 0, 0, 20, 100, 78, 78, 78, 0, 0, 78, 0, 0, 78, 78, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0, 0, 0, 0],
                                   [0, 0, 0, 0, 39, 0, 78, 78, 0, 195, 0, 78, 0, 0, 0, 0, 78, 0, 0, 0, 0, 78, 0, 0, 0,
                                    0, 0, 78, 0, 0, 0, 0, 0],
                                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 195, 0, 0, 0, 0, 40, 0, 0, 40, 0,
                                    0, 0, 78, 78, 0, 78, 20],
                                   [40, 195, 0, 0, 39, 0, 0, 39, 39, 0, 195, 39, 39, 0, 0, 0, 0, 0, 0, 78, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0, 0, 0, 0],
                                   [0, 0, 0, 78, 78, 78, 0, 0, 0, 78, 0, 40, 0, 0, 40, 78, 0, 0, 0, 0, 40, 0, 0, 40, 20,
                                    0, 0, 0, 0, 0, 20, 0, 20],
                                   [0, 0, 78, 78, 20, 78, 0, 0, 0, 78, 0, 0, 0, 0, 195, 78, 78, 0, 0, 0, 0, 0, 0, 78, 0,
                                    0, 0, 0, 0, 0, 0, 0, 0],
                                   [0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0],
                                   [78, 78, 78, 40, 195, 78, 78, 78, 78, 78, 78, 195, 40, 40, 100, 40, 195, 40, 40, 40,
                                    40, 40, 40, 40, 195, 195, 40, 78, 0, 0, 20, 0, 20],
                                   [0, 0, 0, 0, 40, 40, 0, 0, 78, 78, 40, 78, 0, 0, 40, 40, 0, 0, 0, 78, 78, 0, 0, 78,
                                    0, 0, 0, 0, 0, 0, 195, 0, 0],
                                   [195, 78, 0, 0, 78, 0, 0, 20, 0, 0, 78, 0, 78, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0, 0, 0, 0],
                                   [195, 0, 0, 0, 78, 0, 0, 0, 0, 0, 0, 78, 195, 0, 0, 0, 40, 0, 195, 0, 0, 0, 0, 0, 40,
                                    0, 0, 0, 0, 0, 0, 0, 0],
                                   [40, 0, 0, 0, 78, 0, 0, 195, 78, 0, 0, 78, 40, 0, 0, 0, 78, 195, 195, 78, 40, 0, 195,
                                    0, 0, 0, 195, 195, 0, 0, 0, 0, 0],
                                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0,
                                    0, 195, 0, 0, 20],
                                   [40, 0, 0, 0, 78, 0, 78, 0, 0, 78, 0, 20, 78, 78, 0, 0, 195, 0, 0, 0, 78, 78, 0, 0,
                                    40, 40, 0, 0, 0, 0, 0, 0, 0]],
                               loads=[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
                                      3, 3, 3],
                               required_courses=[8, 21, 33],
                               max_iter=500,
                               p_tgt=4
)
