#FROM rayproject/ray:latest
FROM python:3.7
WORKDIR /algorithm-1
COPY ./src/* .
COPY requirements.txt .
RUN pip3 install -r requirements.txt
#EXPOSE 6379
EXPOSE 8000
#EXPOSE 8265
ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
#ENTRYPOINT ["serve", "run", "main:deployment_graph", "--address", "0.0.0.0:8000", "--port", "8000"]
